version: '3'
services:
  verynginx:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: very-nginx
    container_name: very-nginx
    restart: always
    volumes: 
      - "/data/VeryNginx/configs:/opt/verynginx/verynginx/configs"
      - "/data/VeryNginx/nginx_conf:/opt/verynginx/verynginx/nginx_conf"
    ports:
      - 80:80
      - 443:443